#!/usr/bin/env bash
#
# Production deploy wizard: Kreloses Data Analytics (issue #7).
#
# The OWNER runs this. It walks through every production step (Vercel project and environment
# variables, Supabase migrations and Auth settings, the deploy, post-deploy checks, Kreloses
# connections, the history backfill switch), checks what is already done, and changes nothing
# without asking first.
#
#   scripts/deploy-wizard.sh              the whole deploy, stage by stage. Re-run it any time:
#                                         finished stages are detected and skipped.
#   scripts/deploy-wizard.sh --dry-run    change nothing: read-only checks still run, and every
#                                         command that would change something is printed instead
#   scripts/deploy-wizard.sh --check URL  only the post-deploy HTTP checks, against URL
#   scripts/deploy-wizard.sh --help       every option and the environment variables it reads
#
# Checklist and troubleshooting: docs/runbooks/production-deploy.md. The repository is PUBLIC, so
# this file holds no secrets, project refs or emails: it asks for them (or reads them from your
# environment), never prints them, and never writes them inside the repository.
#
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13

# ── Settings (each can be overridden from the environment; none of them is secret) ───────────────
PROJECT_NAME="${VERCEL_PROJECT_NAME:-kreloses-data-analytics}"
# The owner's SEPARATE Vercel CLI login, so their other Vercel login is never disturbed.
VERCEL_GLOBAL_CONFIG="${VERCEL_GLOBAL_CONFIG:-$HOME/.vercel-alsontanwork4}"
# The checkout to deploy (the tests point it at a sandbox).
ROOT="${DEPLOY_WIZARD_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
# Where the owner may keep a copy of the generated secrets and settings: OUTSIDE the repository,
# readable only by them (chmod 600). Only written after they agree.
SAVE_FILE="${DEPLOY_WIZARD_SAVE_FILE:-$HOME/.config/kreloses-data-analytics/production.env}"
# The library's ask/_existing/write_env use ONLY this file: never a .env inside the repository.
ENV_FILE="$SAVE_FILE"
PASSWORD_PLACEHOLDER='[YOUR-PASSWORD]'
LOGIN_PAGE_MARKER='Kreloses Analytics'

# ── Environment variables: THE list. `--check-env` (run by stage 1) and scripts/deploy-wizard.test.ts
# fail when the code reads a variable none of these lists names; the test also holds .env.example
# and README "Environment variables" to them. ──────────────────────────────────────────────────────
# Set in Vercel → Production by stage 6.
PRODUCTION_ENV_VARS="DATABASE_URL DATABASE_PREPARE NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY OWNER_EMAIL CREDENTIALS_ENCRYPTION_KEY CRON_SECRET MCP_BEARER_TOKEN"
# Of those, the ones stored as Vercel "sensitive" variables (write-only: nobody can read them back).
SENSITIVE_ENV_VARS="DATABASE_URL CREDENTIALS_ENCRYPTION_KEY CRON_SECRET MCP_BEARER_TOKEN"
# Optional tuning with safe defaults: the wizard leaves them unset.
OPTIONAL_ENV_VARS="DATABASE_POOL_MAX SYNC_TIME_BUDGET_SECONDS SYNC_NIGHTLY_WINDOW_DAYS BACKFILL_REQUEST_DELAY_SECONDS BACKFILL_MAX_REQUESTS_PER_NIGHT BACKFILL_NIGHT_WINDOW"
# Local tooling and tests only. They must NOT be set in production (stage 6 offers to remove them).
LOCAL_ONLY_ENV_VARS="DATABASE_ADMIN_URL KRELOSES_BASE_URL_WWW KRELOSES_BASE_URL_SEA CLINIC_NOW KRELOSES_TEST_EMAIL KRELOSES_TEST_PASSWORD KRELOSES_TEST_SESSION_PROBE_MINUTES KRELOSES_TEST_MONTH E2E_MAILPIT_URL E2E_PORT E2E_KRELOSES_PORT NEXT_DIST_DIR"
# Provided by the platform (Node.js, Next.js, Vercel, the shell), never set by hand.
PLATFORM_ENV_VARS="NODE_ENV VERCEL VERCEL_ENV PATH"

# ── Options ───────────────────────────────────────────────────────────────────────────────────────
DRY_RUN=0
MODE=wizard
CHECK_URL=""
ROTATE=""
while (($#)); do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --rotate)
      case "${2:-}" in
        CRON_SECRET | MCP_BEARER_TOKEN) ROTATE="$ROTATE $2" ;;
        CREDENTIALS_ENCRYPTION_KEY)
          printf 'CREDENTIALS_ENCRYPTION_KEY is never rotated by this wizard: a new key makes every stored\nKreloses password unreadable (runbook, "Rotating secrets").\n' >&2
          exit 2
          ;;
        *)
          printf -- '--rotate takes CRON_SECRET or MCP_BEARER_TOKEN\n' >&2
          exit 2
          ;;
      esac
      shift
      ;;
    --check)
      MODE=check
      CHECK_URL="${2:-}"
      [[ $# -ge 2 ]] && shift
      ;;
    --check=*) MODE=check; CHECK_URL="${1#--check=}" ;;
    --check-env) MODE=check-env ;;
    --list-env) MODE=list-env ;;
    -h | --help) MODE=help ;;
    *)
      printf 'Unknown option: %s (try --help)\n' "$1" >&2
      exit 2
      ;;
  esac
  shift
done

usage() {
  cat <<EOF
Production deploy wizard (issue #7). Runbook: docs/runbooks/production-deploy.md

  scripts/deploy-wizard.sh              the whole deploy, stage by stage (safe to re-run)
  scripts/deploy-wizard.sh --dry-run    change nothing; print every command that would change something
  scripts/deploy-wizard.sh --rotate NAME
                                        replace CRON_SECRET or MCP_BEARER_TOKEN with a new one (repeatable;
                                        never CREDENTIALS_ENCRYPTION_KEY), then redeploy and update GitHub
  scripts/deploy-wizard.sh --check URL  only the post-deploy HTTP checks against URL
  scripts/deploy-wizard.sh --check-env  fail if the code reads an environment variable the wizard does not know
  scripts/deploy-wizard.sh --list-env   print the wizard's environment variable lists

Values it asks for can be exported beforehand instead (never put secrets in files in the repo):
  VERCEL_TEAM                           the Vercel team (scope) slug
  NEXT_PUBLIC_SUPABASE_URL              https://<ref>.supabase.co of the PRODUCTION project
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY  sb_publishable_...
  OWNER_EMAIL                           the owner's sign-in email
  SUPABASE_TRANSACTION_POOLER_URL       the transaction pooler string (port 6543) with [YOUR-PASSWORD] in it
  SUPABASE_SESSION_POOLER_URL           the session pooler string (port 5432) with [YOUR-PASSWORD] in it
  SUPABASE_DB_PASSWORD                  the database password (raw; the wizard percent-encodes it)
  PRODUCTION_URL                        https://... once deployed
  GITHUB_OWNER                          the GitHub account that owns the repository
The generated secrets (CREDENTIALS_ENCRYPTION_KEY, CRON_SECRET, MCP_BEARER_TOKEN) are never read
from your environment: they are generated fresh, or reused from the wizard's own saved file.

Settings: VERCEL_GLOBAL_CONFIG (default ~/.vercel-alsontanwork4), VERCEL_PROJECT_NAME (default
kreloses-data-analytics), DEPLOY_WIZARD_SAVE_FILE (default
~/.config/kreloses-data-analytics/production.env), WIZARD_NO_BROWSER=1 (print links, don't open them).
EOF
}

# ── Output and bookkeeping ────────────────────────────────────────────────────────────────────────
DONE_ITEMS=()
TODO_ITEMS=()
PLANNED=()
SECRETS=()
DISPLAY_PREFIX=""
SAVE_ENABLED=0
VERCEL_OK=0
PROJECT_EXISTS=0
VERCEL_ENV_KEYS=""
VERCEL_ENV_READ=0
ENV_CHANGED=0
NEW_SECRETS=""
CHECKS_FAILED=0
TMP_DIR=""

die() {
  printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}
done_item() {
  DONE_ITEMS+=("$1")
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
}
todo_item() {
  TODO_ITEMS+=("$1")
  SKIPPED+=("$1")
  printf '  %s…%s still to do: %s\n' "$YELLOW" "$RESET" "$1"
}
indent() { sed 's/^/      /'; }

# register_secret VALUE: never print VALUE (every printed command and captured output is masked).
register_secret() {
  if [[ ${#1} -ge 6 ]]; then SECRETS+=("$1"); fi
  return 0
}
mask() {
  local text="$1" secret
  for secret in ${SECRETS[@]+"${SECRETS[@]}"}; do text="${text//"$secret"/<hidden>}"; done
  printf '%s' "$text"
}

in_list() {
  local item="$1" entry
  for entry in $2; do [[ "$entry" == "$item" ]] && return 0; done
  return 1
}

# ── Running commands: probes read, actions change ─────────────────────────────────────────────────
# A probe only reads (who am I signed in as, which variables exist, an HTTP status). It runs in
# every mode, including --dry-run, with stdin closed so it can never swallow an answer.
probe() { "$@" </dev/null; }

# The command as you could type it, each argument masked BEFORE any quoting (so quoting can never
# change a secret into something the mask misses), quoted only when the shell would need it.
cmd_text() {
  local text="" arg plain='^[A-Za-z0-9_./:=@%+,<>-]+$'
  for arg in "$@"; do
    arg=$(mask "$arg")
    if [[ "$arg" =~ $plain ]]; then text="$text $arg"; else text="$text $(printf '%q' "$arg")"; fi
  done
  printf '%s%s' "$DISPLAY_PREFIX" "${text# }"
}
show_cmd() { printf '  %s$ %s%s\n' "$DIM" "$(mask "$1")" "$RESET"; }
planned() {
  PLANNED+=("$(mask "$1")")
  printf '  %s[dry-run]%s %s\n' "$YELLOW" "$RESET" "$(mask "$1")"
}
# Last line of defence for spec rule #1: the production CREDENTIALS_ENCRYPTION_KEY is never
# replaced, updated or removed by this wizard (a new key makes every stored Kreloses password unreadable).
guard_command() {
  if [[ "$1" == *CREDENTIALS_ENCRYPTION_KEY* ]]; then
    case "$1" in
      *" rm "* | *" remove "* | *" update "* | *--force*) die "Refusing to change the production CREDENTIALS_ENCRYPTION_KEY." ;;
    esac
    if [[ "$1" == *"env add"* ]] && in_list CREDENTIALS_ENCRYPTION_KEY "$VERCEL_ENV_KEYS"; then
      die "Refusing to add a second CREDENTIALS_ENCRYPTION_KEY: production already has one."
    fi
  fi
  return 0
}
# act CMD...: changes something (Vercel, Supabase, GitHub, a local file). --dry-run prints it instead.
act() {
  local text
  text=$(cmd_text "$@")
  guard_command "$text"
  if ((DRY_RUN)); then
    planned "$text"
    return 0
  fi
  show_cmd "$text"
  "$@" </dev/null
}
# act_tty CMD...: like act, for a command that may ask its own questions (keeps the terminal).
act_tty() {
  local text
  text=$(cmd_text "$@")
  guard_command "$text"
  if ((DRY_RUN)); then
    planned "$text"
    return 0
  fi
  show_cmd "$text"
  "$@"
}
# act_input VALUE CMD...: like act, with VALUE on the command's stdin. This is how every secret
# reaches vercel and gh: never as an argument (arguments show in process lists and on screen).
act_input() {
  local value="$1" text
  shift
  text="$(cmd_text "$@") < (value on stdin, hidden)"
  guard_command "$text"
  if ((DRY_RUN)); then
    planned "$text"
    return 0
  fi
  show_cmd "$text"
  printf '%s' "$value" | "$@"
}
# act_capture VAR CMD...: like act; the command's stdout goes into VAR (its stderr still shows).
act_capture() {
  local var="$1" text output
  shift
  text=$(cmd_text "$@")
  guard_command "$text"
  printf -v "$var" '%s' ""
  if ((DRY_RUN)); then
    planned "$text"
    return 0
  fi
  show_cmd "$text"
  output=$("$@" </dev/null) || return $?
  printf -v "$var" '%s' "$output"
}

open_page() {
  if ((DRY_RUN)) || [[ -n "${WIZARD_NO_BROWSER:-}" ]]; then
    printf '  %s↗%s %s\n' "$GREEN" "$RESET" "$1"
    return 0
  fi
  open_url "$1"
}

# Every vercel command uses the separate login; once the team is known, its scope too. Actions spell
# the full command out (so --dry-run prints something you can copy); probes use these shorthands.
VFLAGS=(--global-config "$VERCEL_GLOBAL_CONFIG")
vc() { vercel "$@" --global-config "$VERCEL_GLOBAL_CONFIG"; }
vcs() { vercel "$@" "${VFLAGS[@]}"; }

# ── Values: from your environment, the saved file, or a prompt ────────────────────────────────────
VALIDATION_ERROR=""
validate() {
  local name="$1" value="$2" re
  VALIDATION_ERROR=""
  case "$name" in
    VERCEL_TEAM)
      re='^[A-Za-z0-9][A-Za-z0-9._-]*$'
      [[ "$value" =~ $re ]] || VALIDATION_ERROR="a team slug has only letters, digits, dots, dashes and underscores"
      ;;
    NEXT_PUBLIC_SUPABASE_URL)
      re='^https://[A-Za-z0-9.-]+$'
      if ! [[ "$value" =~ $re ]]; then
        VALIDATION_ERROR="expected https://<project-ref>.supabase.co (no path)"
      elif [[ "$value" == *localhost* || "$value" == *127.0.0.1* ]]; then
        VALIDATION_ERROR="that is the local stack; use the PRODUCTION project's URL"
      fi
      ;;
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
      re='^sb_publishable_[A-Za-z0-9_-]+$'
      [[ "$value" =~ $re ]] || VALIDATION_ERROR="expected the new publishable key (sb_publishable_…), not the legacy anon JWT (README Production)"
      ;;
    OWNER_EMAIL)
      re='^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
      [[ "$value" =~ $re ]] || VALIDATION_ERROR="that is not an email address"
      ;;
    SUPABASE_TRANSACTION_POOLER_URL | SUPABASE_SESSION_POOLER_URL)
      local port=6543
      [[ "$name" == SUPABASE_SESSION_POOLER_URL ]] && port=5432
      re="^postgres(ql)?://postgres(\\.[a-z0-9]+)?:\\[YOUR-PASSWORD\\]@[A-Za-z0-9.-]+:${port}/postgres(\\?.*)?\$"
      if [[ "$value" != *"$PASSWORD_PLACEHOLDER"* ]]; then
        VALIDATION_ERROR="copy it WITHOUT revealing the password: it must still contain $PASSWORD_PLACEHOLDER (the password is asked separately)"
      elif ! [[ "$value" =~ $re ]]; then
        VALIDATION_ERROR="expected postgresql://postgres.<ref>:$PASSWORD_PLACEHOLDER@<host>:${port}/postgres (port ${port})"
      fi
      ;;
    SUPABASE_DB_PASSWORD)
      if [[ "$value" == *"$PASSWORD_PLACEHOLDER"* ]]; then
        VALIDATION_ERROR="that is the placeholder, not the password"
      fi
      ;;
    PRODUCTION_URL)
      re='^https://[A-Za-z0-9.-]+$'
      [[ "$value" =~ $re ]] || VALIDATION_ERROR="expected https://<domain> (no path)"
      ;;
    GITHUB_OWNER)
      re='^[A-Za-z0-9-]+$'
      [[ "$value" =~ $re ]] || VALIDATION_ERROR="that is not a GitHub account name"
      ;;
    CRON_SECRET_FOR_GITHUB)
      [[ ${#value} -ge 16 ]] || VALIDATION_ERROR="the app's CRON_SECRET has at least 16 characters"
      ;;
  esac
  [[ -z "$VALIDATION_ERROR" ]]
}

# get_value NAME KIND PROMPT [DEFAULT]: sets V_NAME (never exported) from, in order, the exported
# environment variable NAME, the saved file, or a prompt (KIND "secret" = hidden input). Invalid
# values are refused with the reason; after three tries, or at the end of input, it stops.
get_value() {
  local name="$1" kind="$2" prompt="$3" default="${4:-}" value="" source="" tries=0
  value="${!name:-}"
  [[ -n "$value" ]] && source="your environment"
  if [[ -z "$value" ]]; then
    value=$(_existing "$name" || true)
    [[ -n "$value" ]] && source="$SAVE_FILE"
  fi
  case "$name" in *_URL) value="${value%/}" ;; esac
  if [[ -n "$value" ]] && ! validate "$name" "$value"; then
    warn "ignoring $name from $source: $VALIDATION_ERROR"
    value=""
    source=""
  fi
  while [[ -z "$value" ]]; do
    tries=$((tries + 1))
    ((tries <= 3)) || die "No valid value for $name."
    if [[ -n "$default" ]]; then
      printf '  %s%s%s %s[Enter: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$default" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    local answered=1
    if [[ "$kind" == secret ]]; then
      read -rs value || answered=0
      printf '\n'
    else
      read -r value || answered=0
    fi
    [[ -z "$value" && -n "$default" ]] && value="$default"
    if [[ -z "$value" && $answered -eq 0 ]]; then die "No answer for $name (end of input)."; fi
    case "$name" in *_URL) value="${value%/}" ;; esac
    if [[ -n "$value" ]] && ! validate "$name" "$value"; then
      warn "$VALIDATION_ERROR"
      value=""
    fi
  done
  if [[ -n "$source" ]]; then note "$name: from $source"; fi
  [[ "$kind" == secret ]] && register_secret "$value"
  printf -v "V_$name" '%s' "$value"
}

# ── The saved file (outside the repository, chmod 600) ─────────────────────────────────────────────
enable_save() {
  [[ "$SAVE_FILE" == /* ]] || die "DEPLOY_WIZARD_SAVE_FILE must be an absolute path."
  case "$SAVE_FILE" in "$ROOT"/*) die "Refusing to save secrets inside the repository ($SAVE_FILE)." ;; esac
  if ((DRY_RUN)); then
    planned "save the values below to $SAVE_FILE (chmod 600, outside the repository)"
    return 0
  fi
  local dir
  dir=$(dirname "$SAVE_FILE")
  [[ -d "$dir" ]] || mkdir -p -m 700 "$dir"
  (umask 077 && touch "$SAVE_FILE")
  chmod 600 "$SAVE_FILE"
  SAVE_ENABLED=1
}
save_value() {
  ((SAVE_ENABLED)) && ((!DRY_RUN)) && [[ -n "${2:-}" ]] || return 0
  write_env "$1" "$2"
  chmod 600 "$SAVE_FILE"
}

# ── Environment variable lists vs the code ─────────────────────────────────────────────────────────
# Every NAME the app's code reads as process.env.NAME, env.NAME, env?.NAME or env["NAME"].
code_env_vars() {
  # Trailing slashes: BSD grep -r does not follow a directory given as a symlink otherwise.
  local paths=("$ROOT/src/" "$ROOT/scripts/")
  [[ -f "$ROOT/next.config.ts" ]] && paths+=("$ROOT/next.config.ts")
  {
    grep -rhoE '(^|[^A-Za-z0-9_$])env\??\.[A-Z][A-Z0-9_]*' --include='*.ts' --include='*.tsx' --include='*.mts' "${paths[@]}" 2>/dev/null |
      sed -E 's/.*\.//' || true
    grep -rhoE "env\\[[\"'\`][A-Z][A-Z0-9_]*[\"'\`]\\]" --include='*.ts' --include='*.tsx' --include='*.mts' "${paths[@]}" 2>/dev/null |
      sed -E 's/^env\[.(.*).\]$/\1/' || true
  } | sort -u
}
known_env_vars() { printf '%s %s %s %s' "$PRODUCTION_ENV_VARS" "$OPTIONAL_ENV_VARS" "$LOCAL_ONLY_ENV_VARS" "$PLATFORM_ENV_VARS"; }
check_env_complete() {
  local name unknown="" known
  known=$(known_env_vars)
  for name in $(code_env_vars); do in_list "$name" "$known" || unknown="$unknown $name"; done
  if [[ -n "$unknown" ]]; then
    printf '  %s✗ The code reads environment variables this wizard does not know:%s%s\n' "$RED" "$unknown" "$RESET" >&2
    printf '    Add each to one of the lists at the top of scripts/deploy-wizard.sh (and to .env.example and\n    README "Environment variables"), then run the wizard again.\n' >&2
    return 1
  fi
  return 0
}
list_env() {
  local name
  for name in $PRODUCTION_ENV_VARS; do
    if in_list "$name" "$SENSITIVE_ENV_VARS"; then printf 'production %s sensitive\n' "$name"; else printf 'production %s plain\n' "$name"; fi
  done
  for name in $OPTIONAL_ENV_VARS; do printf 'optional %s\n' "$name"; done
  for name in $LOCAL_ONLY_ENV_VARS; do printf 'local %s\n' "$name"; done
  for name in $PLATFORM_ENV_VARS; do printf 'platform %s\n' "$name"; done
}

# ── Vercel state ──────────────────────────────────────────────────────────────────────────────────
# Names of the variables set for Production (values are never printed; sensitive ones cannot be read).
load_vercel_env() {
  VERCEL_ENV_KEYS=""
  VERCEL_ENV_READ=0
  ((VERCEL_OK)) || return 0
  local json keys
  if json=$(probe vcs env list production --format json --project "$PROJECT_NAME" 2>/dev/null) &&
    keys=$(printf '%s' "$json" | jq -r '(.envs // [])[] | .key' 2>/dev/null); then
    VERCEL_ENV_KEYS=$(printf '%s\n' "$keys" | sort -u | tr '\n' ' ')
    VERCEL_ENV_READ=1
  elif ((PROJECT_EXISTS)); then
    die "Could not read the Vercel project's environment variables. Check 'vercel whoami --global-config $VERCEL_GLOBAL_CONFIG' and the team, then run the wizard again (nothing is generated without knowing what is already set)."
  fi
}
vercel_has() { in_list "$1" "$VERCEL_ENV_KEYS"; }

# ── HTTP checks (stage 10 and --check) ─────────────────────────────────────────────────────────────
HTTP_STATUS=""
http_request() {
  local url="$1"
  shift
  local proto=()
  [[ "$url" == https://* ]] && proto=(--proto '=https')
  : >"$TMP_DIR/body"
  : >"$TMP_DIR/headers"
  HTTP_STATUS=$(curl -sS ${proto[@]+"${proto[@]}"} --max-time 30 -o "$TMP_DIR/body" -D "$TMP_DIR/headers" -w '%{http_code}' "$@" "$url" </dev/null 2>"$TMP_DIR/error") || true
  [[ -n "$HTTP_STATUS" ]] || HTTP_STATUS=000
}
body_has() { grep -qF -- "$1" "$TMP_DIR/body"; }
header_has() { grep -qiE -- "$1" "$TMP_DIR/headers"; }
check_pass() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
check_fail() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"
  [[ -n "${2:-}" ]] && printf '    %s\n' "$2"
  CHECK_FAILURES=$((CHECK_FAILURES + 1))
}
is_loopback_url() {
  local re='^http://(localhost|127\.0\.0\.1|\[::1\])(:[0-9]+)?$'
  [[ "$1" =~ $re ]]
}
site_answers() {
  http_request "${1%/}/login"
  [[ "$HTTP_STATUS" == 200 ]] && body_has "$LOGIN_PAGE_MARKER"
}

# run_checks URL: read-only requests, no secrets sent. Returns 1 if any check failed.
CHECK_FAILURES=0
run_checks() {
  local base="${1%/}" host
  CHECK_FAILURES=0
  if [[ "$base" == https://* ]]; then
    host="${base#https://}"
    http_request "http://$host/login"
    if [[ "$HTTP_STATUS" == 30[178] ]] && header_has "^location: *https://"; then
      check_pass "plain HTTP redirects to HTTPS"
    else
      check_fail "http://$host answered $HTTP_STATUS (expected a redirect to https://)"
    fi
  elif is_loopback_url "$base"; then
    note "local URL: HTTPS not checked"
  else
    check_fail "$base is not HTTPS" "Production must be served over https://"
    return 1
  fi

  http_request "$base/login"
  if [[ "$HTTP_STATUS" == 200 ]] && body_has "$LOGIN_PAGE_MARKER"; then
    check_pass "/login renders the sign-in page (HTTPS reachable)"
  elif [[ "$HTTP_STATUS" == 000 ]]; then
    check_fail "$base is not reachable: $(mask "$(head -c 300 "$TMP_DIR/error")")" "Is the URL right, and has the deploy finished?"
  elif [[ "$HTTP_STATUS" == 401 || "$HTTP_STATUS" == 403 ]]; then
    check_fail "/login answered $HTTP_STATUS" "Vercel Deployment Protection covers this URL. Use the production domain (Standard Protection leaves it public) or check Settings → Deployment Protection."
  else
    check_fail "/login answered HTTP $HTTP_STATUS without the sign-in page" "Look at the deployment's logs in Vercel (missing environment variables?)."
  fi

  http_request "$base/overview"
  if [[ "$HTTP_STATUS" == 30[278] ]] && header_has "^location: *[^ ]*/login"; then
    check_pass "signed-out visitors are sent to /login (the dashboard is private)"
  else
    check_fail "/overview answered $HTTP_STATUS to a signed-out visitor (expected a redirect to /login)"
  fi

  check_cron_endpoint "$base" /api/cron/nightly "nightly sync"
  if [[ -f "$ROOT/src/app/api/cron/backfill/route.ts" ]]; then
    check_cron_endpoint "$base" /api/cron/backfill "history backfill"
  fi

  http_request "$base/api/mcp" -X POST -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' \
    --data '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'
  if [[ "$HTTP_STATUS" == 401 ]] && header_has '^www-authenticate: *Bearer realm="kreloses-mcp"'; then
    check_pass "/api/mcp answers 401 without the token (MCP_BEARER_TOKEN is set)"
  elif [[ "$HTTP_STATUS" == 503 ]]; then
    check_fail "/api/mcp answered 503: MCP_BEARER_TOKEN is not set on the server" "Set it (stage 6) and deploy again."
  else
    check_fail "/api/mcp answered $HTTP_STATUS without a token (expected 401 with WWW-Authenticate: Bearer)"
  fi

  if ((CHECK_FAILURES)); then return 1; fi
  return 0
}
check_cron_endpoint() {
  local base="$1" path="$2" what="$3"
  http_request "$base$path"
  if [[ "$HTTP_STATUS" == 401 ]] && body_has '"unauthorized"'; then
    check_pass "$path answers 401 without the cron secret ($what)"
  elif [[ "$HTTP_STATUS" == 401 ]] && body_has '"unauthenticated"'; then
    check_fail "$path is behind the sign-in gate" "The deployed code predates this endpoint: deploy the latest main."
  elif [[ "$HTTP_STATUS" == 2* ]]; then
    check_fail "$path answered $HTTP_STATUS WITHOUT the secret" "Stop and investigate: this endpoint must refuse unauthenticated calls."
  else
    check_fail "$path answered $HTTP_STATUS (expected 401)"
  fi
}

setup_tmp() {
  TMP_DIR=$(mktemp -d)
  trap 'rm -rf "$TMP_DIR"' EXIT
}

# ── Stages ─────────────────────────────────────────────────────────────────────────────────────────
REPO_SLUG=""
REPO_OWNER=""

stage_preflight() {
  stage "Preflight: tools and the code to deploy"
  say "Checks this machine and the checkout. Changes nothing."
  local tool missing="" problems=""
  for tool in node npm git supabase vercel gh openssl curl jq; do
    command -v "$tool" >/dev/null 2>&1 || missing="$missing $tool"
  done
  if [[ -n "$missing" ]]; then
    warn "missing:$missing"
    note "Node 22+: https://nodejs.org · Supabase CLI: brew install supabase/tap/supabase · Vercel CLI: npm i -g vercel"
    note "GitHub CLI: brew install gh · openssl, curl and jq ship with macOS (brew install jq otherwise)"
    die "Install the missing tools, then run the wizard again."
  fi
  local node_major
  node_major=$(probe node -v 2>/dev/null | sed -E 's/^v([0-9]+).*/\1/')
  [[ "$node_major" =~ ^[0-9]+$ ]] && ((node_major >= 22)) || die "Node.js 22 or newer is needed (found: $(probe node -v 2>/dev/null || echo none))."
  done_item "tools: node $node_major, npm, git, supabase, vercel, gh, openssl, curl, jq"

  check_env_complete || die "The environment variable list is out of date (see above)."
  done_item "every environment variable the code reads is known to this wizard"

  local remote re='github\.com[:/]([^/]+)/([^/]+)$'
  remote=$(probe git -C "$ROOT" remote get-url origin 2>/dev/null || true)
  if [[ "$remote" =~ $re ]]; then
    REPO_OWNER="${BASH_REMATCH[1]}"
    REPO_SLUG="$REPO_OWNER/${BASH_REMATCH[2]%.git}"
  else
    die "The 'origin' remote is not a GitHub repository ($remote)."
  fi

  local branch dirty head upstream
  branch=$(probe git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)
  dirty=$(probe git -C "$ROOT" status --porcelain 2>/dev/null || true)
  probe git -C "$ROOT" fetch --quiet origin main 2>/dev/null || warn "could not fetch origin/main (offline?)"
  head=$(probe git -C "$ROOT" rev-parse HEAD 2>/dev/null || true)
  upstream=$(probe git -C "$ROOT" rev-parse origin/main 2>/dev/null || true)
  [[ "$branch" == main ]] || problems="$problems\n    on branch '$branch', not main: git switch main"
  [[ -z "$dirty" ]] || problems="$problems\n    uncommitted changes: commit or stash them (git status)"
  [[ -n "$head" && "$head" == "$upstream" ]] || problems="$problems\n    not the latest main: git pull --ff-only"
  if [[ -n "$problems" ]]; then
    printf '  %s⚠ The checkout is not a clean, up-to-date main:%b%s\n' "$YELLOW" "$problems" "$RESET"
    ((DRY_RUN)) || die "Deploy only the latest main. Fix the above, then run the wizard again."
    todo_item "deploy from a clean, up-to-date main"
  else
    done_item "clean checkout of the latest main ($REPO_SLUG)"
  fi

  say ""
  say "Optional: install exactly the locked dependencies and run the typecheck and the tests first."
  note "(npm test needs the local Supabase stack running: 'supabase status'. Skip it if you don't run it locally.)"
  if confirm "Run npm ci, npm run typecheck and npm test now?"; then
    act npm ci || die "npm ci failed."
    act npm run typecheck || die "The typecheck failed: don't deploy this checkout."
    act npm test || die "The tests failed: don't deploy this checkout."
    ((DRY_RUN)) || done_item "npm ci, typecheck and tests passed"
  fi
}

stage_vercel_login() {
  stage "Vercel: sign in (a separate CLI login)"
  say "The wizard uses its own Vercel CLI login, kept in $VERCEL_GLOBAL_CONFIG,"
  say "so your other Vercel CLI login is left alone."
  local who="" attempt
  for attempt in 1 2 3; do
    who=$(probe vc whoami 2>/dev/null | tail -n 1 || true)
    [[ -n "$who" ]] && break
    step "In ANOTHER terminal, sign in with the account that owns the GitHub repository:"
    say "    vercel login --global-config $VERCEL_GLOBAL_CONFIG"
    ((DRY_RUN)) && break
    pause "Press Enter once you are signed in"
  done
  if [[ -z "$who" ]]; then
    ((DRY_RUN)) || die "Still not signed in to Vercel (vercel whoami --global-config $VERCEL_GLOBAL_CONFIG)."
    todo_item "vercel login --global-config $VERCEL_GLOBAL_CONFIG"
    return 0
  fi
  VERCEL_OK=1
  done_item "Vercel CLI signed in as $who"
  say ""
  say "Your teams (use the personal Hobby team of the account that owns the repository):"
  probe vc teams ls 2>&1 | indent || true
  get_value VERCEL_TEAM text "Vercel team slug:"
  VFLAGS=(--global-config "$VERCEL_GLOBAL_CONFIG" --scope "$V_VERCEL_TEAM")
  done_item "Vercel team: $V_VERCEL_TEAM"
  save_value VERCEL_TEAM "$V_VERCEL_TEAM"
}

stage_project() {
  stage "Vercel: the project, linked to the GitHub repository"
  if ((!VERCEL_OK)); then
    todo_item "create/link the Vercel project (sign in to Vercel first)"
    return 0
  fi
  local team="$V_VERCEL_TEAM" details="" project_id="" linked_name="" linked_id="" repo_link="" framework="" fluid="" settings
  settings="https://vercel.com/$team/$PROJECT_NAME/settings"
  if probe vcs project inspect "$PROJECT_NAME" >/dev/null 2>&1; then PROJECT_EXISTS=1; else PROJECT_EXISTS=0; fi
  project_details() {
    details=$(probe vcs api "/v9/projects/$PROJECT_NAME" --raw 2>/dev/null || true)
    project_id=$(printf '%s' "$details" | jq -r '.id // empty' 2>/dev/null || true)
    repo_link=$(printf '%s' "$details" | jq -r 'if .link.repo then "\(.link.org // "")/\(.link.repo)" else "" end' 2>/dev/null || true)
    framework=$(printf '%s' "$details" | jq -r '.framework // empty' 2>/dev/null || true)
    fluid=$(printf '%s' "$details" | jq -r '.resourceConfig.fluid // empty' 2>/dev/null || true)
  }
  ((PROJECT_EXISTS)) && project_details
  if [[ -f "$ROOT/.vercel/project.json" ]]; then
    linked_name=$(jq -r '.projectName // empty' "$ROOT/.vercel/project.json" 2>/dev/null || true)
    linked_id=$(jq -r '.projectId // empty' "$ROOT/.vercel/project.json" 2>/dev/null || true)
  fi

  if ((PROJECT_EXISTS)) && [[ "$linked_name" == "$PROJECT_NAME" || (-n "$project_id" && "$linked_id" == "$project_id") ]]; then
    done_item "this checkout is linked to the Vercel project $PROJECT_NAME"
  else
    if ((PROJECT_EXISTS)); then
      say "The project $PROJECT_NAME exists in $team: linking this checkout to it."
    else
      say "Creating the project $PROJECT_NAME in $team: 'vercel link' detects Next.js from package.json"
      say "and connects the GitHub repository $REPO_SLUG."
    fi
    act vercel link --yes --project "$PROJECT_NAME" "${VFLAGS[@]}" || die "vercel link failed (see above)."
    if ((!DRY_RUN)); then
      PROJECT_EXISTS=1
      project_details
      done_item "linked to the Vercel project $PROJECT_NAME"
    fi
  fi

  # GitHub: once connected, every push to main deploys to production by itself.
  if [[ -n "$repo_link" && "$repo_link" == "$REPO_SLUG" ]]; then
    done_item "GitHub repository $REPO_SLUG is connected (pushes to main deploy to production)"
  elif ((DRY_RUN)) && ((!PROJECT_EXISTS)); then
    note "(vercel link connects the GitHub repository when it creates the project)"
  elif [[ -n "$details" ]]; then
    say "Connecting the GitHub repository $REPO_SLUG (Vercel's GitHub app needs access to it)."
    if act_tty vercel git connect "https://github.com/$REPO_SLUG.git" "${VFLAGS[@]}"; then
      ((DRY_RUN)) || done_item "GitHub repository $REPO_SLUG connected"
    else
      open_page "$settings/git"
      todo_item "connect the GitHub repository in Vercel → $PROJECT_NAME → Settings → Git"
    fi
  else
    open_page "$settings/git"
    if ((!DRY_RUN)) && confirm "Is $REPO_SLUG shown as the connected repository in Settings → Git?"; then
      done_item "GitHub repository connected (confirmed by you)"
    else
      todo_item "connect the GitHub repository in Vercel → $PROJECT_NAME → Settings → Git"
    fi
  fi
  if [[ -n "$framework" && "$framework" != nextjs ]]; then
    warn "the project's framework preset is '$framework': set it to Next.js in Settings → Build and Deployment"
  fi

  # Fluid compute: the sync routes run up to 300 s (maxDuration = 300); on Hobby that needs Fluid compute.
  if [[ "$fluid" == true ]]; then
    done_item "Fluid compute is on (the sync routes may run up to 300 s)"
  else
    say ""
    step "Open Settings → Functions and make sure Fluid Compute is ENABLED (new projects have it on)."
    note "The nightly sync and the backfill run up to 300 s (maxDuration = 300); without Fluid compute"
    note "Hobby functions stop much earlier and every sync would end at its time limit."
    open_page "$settings/functions"
    if ((DRY_RUN)); then
      todo_item "confirm Fluid compute is on (Settings → Functions)"
    elif confirm "Is Fluid Compute enabled?"; then
      done_item "Fluid compute is on (confirmed by you)"
    else
      todo_item "enable Fluid compute (Settings → Functions)"
    fi
  fi
  note "Keep Settings → Deployment Protection on its default (Standard Protection): it guards every"
  note "deployment URL except the production domain, so old deployments with old tokens stay private."
}

generate_secret() {
  local name="$1" format="$2" value
  if ((DRY_RUN)); then
    planned "openssl rand -$format 32   (the new $name, kept in memory, never shown)"
    printf -v "V_$name" '%s' "dry-run-placeholder-$name"
    NEW_SECRETS="$NEW_SECRETS $name"
    return 0
  fi
  value=$(probe openssl rand "-$format" 32 | tr -d '\n')
  [[ ${#value} -ge 32 ]] || die "openssl did not produce a usable $name."
  register_secret "$value"
  printf -v "V_$name" '%s' "$value"
  NEW_SECRETS="$NEW_SECRETS $name"
  done_item "generated a new $name (openssl rand -$format 32; not shown)"
}

stage_secrets() {
  stage "Secrets: encryption key, cron secret, MCP token"
  load_vercel_env
  local name format saved
  for name in CREDENTIALS_ENCRYPTION_KEY CRON_SECRET MCP_BEARER_TOKEN; do
    format=base64
    [[ "$name" == CRON_SECRET ]] && format=hex # README: openssl rand -hex 32
    saved=$(_existing "$name" || true)
    if in_list "$name" "$ROTATE"; then
      say "Rotating $name (--rotate): a new one replaces the one in Vercel in stage 6."
      generate_secret "$name" "$format"
      continue
    fi
    if vercel_has "$name"; then
      if [[ "$name" == CREDENTIALS_ENCRYPTION_KEY ]]; then
        done_item "CREDENTIALS_ENCRYPTION_KEY is already set in Vercel: kept (never replaced; a new key would make every saved Kreloses password unreadable)"
      else
        done_item "$name is already set in Vercel: kept"
      fi
      if [[ -n "$saved" ]]; then
        register_secret "$saved"
        printf -v "V_$name" '%s' "$saved"
      fi
      continue
    fi
    if [[ -n "$saved" ]]; then
      register_secret "$saved"
      printf -v "V_$name" '%s' "$saved"
      NEW_SECRETS="$NEW_SECRETS $name"
      done_item "$name: reusing the one generated by an earlier run ($SAVE_FILE); not in Vercel yet"
    else
      generate_secret "$name" "$format"
    fi
  done

  [[ -n "$NEW_SECRETS" ]] || return 0
  say ""
  if ((SAVE_ENABLED)); then
    note "Keeping them in $SAVE_FILE (readable only by you)."
  elif confirm "Save a copy of the new secrets and your settings to $SAVE_FILE (outside the repository, chmod 600)? You need the MCP token later to connect Claude."; then
    enable_save
  else
    note "Not saved. Vercel stores them write-only, so keep your own copy of the MCP token now."
    if command -v pbcopy >/dev/null 2>&1 && [[ -n "${V_MCP_BEARER_TOKEN:-}" ]] && in_list MCP_BEARER_TOKEN "$NEW_SECRETS" && ((!DRY_RUN)) &&
      confirm "Copy the MCP token to the clipboard (paste it into your password manager)?"; then
      printf '%s' "$V_MCP_BEARER_TOKEN" | pbcopy
      done_item "MCP token copied to the clipboard (not shown)"
    fi
  fi
  for name in $NEW_SECRETS; do
    local holder="V_$name"
    save_value "$name" "${!holder:-}"
  done
  save_value VERCEL_TEAM "${V_VERCEL_TEAM:-}"
}

stage_supabase() {
  stage "Supabase: the production project's values"
  say "From the Supabase dashboard of the EXISTING production project (never the local stack)."
  open_page "https://supabase.com/dashboard/projects"
  step "Project URL: Project Settings → Data API (https://<ref>.supabase.co)."
  get_value NEXT_PUBLIC_SUPABASE_URL text "Project URL:"
  local ref="" re='^https://([a-z0-9]+)\.supabase\.co$'
  [[ "$V_NEXT_PUBLIC_SUPABASE_URL" =~ $re ]] && ref="${BASH_REMATCH[1]}"
  SUPABASE_REF="$ref"
  step "Publishable key: Project Settings → API Keys → Publishable key (sb_publishable_…)."
  get_value NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY text "Publishable key:"
  note "The secret key (sb_secret_…) is NOT needed: the app never uses it (README), so it stays in Supabase."
  get_value OWNER_EMAIL text "Owner email (always allowed in, as owner):"

  say ""
  step "Connection strings: click Connect at the top of the project → Connection String. Copy the"
  step "Transaction pooler one (port 6543) WITHOUT revealing the password: [YOUR-PASSWORD] stays in it."
  get_value SUPABASE_TRANSACTION_POOLER_URL secret "Transaction pooler string (hidden input):"
  local session_default="${V_SUPABASE_TRANSACTION_POOLER_URL/:6543\//:5432/}"
  step "The Session pooler string (port 5432, used only for migrations) is usually the same with 5432."
  get_value SUPABASE_SESSION_POOLER_URL secret "Session pooler string (hidden input):" "$session_default"
  step "The database password (Project Settings → Database; reset it there if you don't have it)."
  get_value SUPABASE_DB_PASSWORD secret "Database password (hidden input):"

  # Percent-encode the password for the URLs: @ → %40, / → %2F, : → %3A, space → %20, …
  local encoded
  encoded=$(printf '%s' "$V_SUPABASE_DB_PASSWORD" | jq -Rr '@uri')
  register_secret "$encoded"
  V_DATABASE_URL="${V_SUPABASE_TRANSACTION_POOLER_URL/"$PASSWORD_PLACEHOLDER"/$encoded}"
  case "$V_DATABASE_URL" in
    *sslmode=*) ;;
    *\?*) V_DATABASE_URL="$V_DATABASE_URL&sslmode=require" ;;
    *) V_DATABASE_URL="$V_DATABASE_URL?sslmode=require" ;;
  esac
  V_SESSION_DB_URL="${V_SUPABASE_SESSION_POOLER_URL/"$PASSWORD_PLACEHOLDER"/$encoded}"
  V_DATABASE_PREPARE=false
  register_secret "$V_DATABASE_URL"
  register_secret "$V_SESSION_DB_URL"
  done_item "DATABASE_URL = the transaction pooler (6543) with the password percent-encoded and sslmode=require"
  note "Special characters in the password are percent-encoded in the URLs (e.g. @ → %40, / → %2F,"
  note "space → %20): a raw '@' would split the URL in the wrong place. The password is never shown."
  done_item "DATABASE_PREPARE = false (Supabase's transaction pooler cannot use prepared statements)"

  # Same project everywhere? The pooler user is postgres.<ref>.
  local pooler_ref="" user_re='^postgres(ql)?://postgres\.([a-z0-9]+):'
  [[ "$V_SUPABASE_TRANSACTION_POOLER_URL" =~ $user_re ]] && pooler_ref="${BASH_REMATCH[2]}"
  if [[ -n "$ref" && -n "$pooler_ref" && "$ref" != "$pooler_ref" ]]; then
    warn "The Project URL and the connection string belong to DIFFERENT projects ($ref vs $pooler_ref)."
    confirm "Carry on anyway?" || die "Stopped: use the values of one production project."
  fi

  # Put the functions next to the database: every page runs several queries.
  local region="" host_re='@aws-[0-9]+-([a-z0-9-]+)\.pooler\.supabase\.com:'
  [[ "$V_SUPABASE_TRANSACTION_POOLER_URL" =~ $host_re ]] && region="${BASH_REMATCH[1]}"
  local vercel_region=""
  case "$region" in
    ap-southeast-1) vercel_region="sin1 (Singapore)" ;;
    ap-southeast-2) vercel_region="syd1 (Sydney)" ;;
    ap-northeast-1) vercel_region="hnd1 (Tokyo)" ;;
    ap-northeast-2) vercel_region="icn1 (Seoul)" ;;
    ap-south-1) vercel_region="bom1 (Mumbai)" ;;
    us-east-1) vercel_region="iad1 (Washington, D.C.)" ;;
    us-east-2) vercel_region="cle1 (Cleveland)" ;;
    us-west-1) vercel_region="sfo1 (San Francisco)" ;;
    us-west-2) vercel_region="pdx1 (Portland)" ;;
    eu-west-1) vercel_region="dub1 (Dublin)" ;;
    eu-west-2) vercel_region="lhr1 (London)" ;;
    eu-west-3) vercel_region="cdg1 (Paris)" ;;
    eu-central-1) vercel_region="fra1 (Frankfurt)" ;;
    eu-north-1) vercel_region="arn1 (Stockholm)" ;;
    ca-central-1) vercel_region="yul1 (Montréal)" ;;
    sa-east-1) vercel_region="gru1 (São Paulo)" ;;
  esac
  if [[ -n "$vercel_region" ]]; then
    say ""
    step "The database is in $region: in Vercel → $PROJECT_NAME → Settings → Functions, set the"
    step "Function Region to $vercel_region (the default is Washington, D.C.; every query would cross the world)."
    if [[ -n "${V_VERCEL_TEAM:-}" ]]; then open_page "https://vercel.com/$V_VERCEL_TEAM/$PROJECT_NAME/settings/functions"; fi
    if ((!DRY_RUN)) && confirm "Is the Function Region set to $vercel_region?"; then
      done_item "Vercel Function Region next to the database ($vercel_region)"
    else
      todo_item "set the Vercel Function Region to $vercel_region (Settings → Functions)"
    fi
  fi

  local name
  for name in NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY OWNER_EMAIL SUPABASE_TRANSACTION_POOLER_URL SUPABASE_SESSION_POOLER_URL; do
    local holder="V_$name"
    save_value "$name" "${!holder:-}"
  done
}

env_value() {
  local holder="V_$1"
  printf '%s' "${!holder:-}"
}

stage_env() {
  stage "Vercel: production environment variables"
  if ((!VERCEL_OK)); then
    todo_item "set the production environment variables (sign in to Vercel first)"
    return 0
  fi
  load_vercel_env
  if ((!PROJECT_EXISTS)); then note "(the project does not exist yet: every variable would be new)"; fi
  say "Production only: preview deployments get none, so a preview can never touch production data."
  local name value sensitivity
  for name in $PRODUCTION_ENV_VARS; do
    if vercel_has "$name" && in_list "$name" "$ROTATE"; then
      act vercel env rm "$name" production --yes --project "$PROJECT_NAME" "${VFLAGS[@]}" || die "Could not remove the old $name."
    elif vercel_has "$name"; then
      case "$name" in
        CREDENTIALS_ENCRYPTION_KEY) done_item "$name already set: kept (never replaced)" ;;
        CRON_SECRET | MCP_BEARER_TOKEN) done_item "$name already set: kept (to replace it: scripts/deploy-wizard.sh --rotate $name)" ;;
        *) done_item "$name already set: kept (to change it: vercel env rm $name production, then run the wizard again)" ;;
      esac
      continue
    fi
    value=$(env_value "$name")
    if [[ -z "$value" ]]; then
      todo_item "$name: no value in this run"
      continue
    fi
    sensitivity=--no-sensitive
    in_list "$name" "$SENSITIVE_ENV_VARS" && sensitivity=--sensitive
    act_input "$value" vercel env add "$name" production "$sensitivity" --yes --project "$PROJECT_NAME" "${VFLAGS[@]}" ||
      die "Could not add $name (see above)."
    ENV_CHANGED=1
    ((DRY_RUN)) || done_item "$name added to Production ($sensitivity)"
  done

  for name in $LOCAL_ONLY_ENV_VARS; do
    vercel_has "$name" || continue
    warn "$name is set in production but is for local tooling/tests only (it can break or weaken the app)."
    if confirm "Remove $name from Production?"; then
      act vercel env rm "$name" production --yes --project "$PROJECT_NAME" "${VFLAGS[@]}" || die "Could not remove $name."
      ENV_CHANGED=1
      ((DRY_RUN)) || done_item "$name removed from Production"
    else
      todo_item "remove $name from Vercel Production"
    fi
  done
  note "Optional tuning, left at its defaults (README Environment variables):"
  note "  $OPTIONAL_ENV_VARS"
}

stage_migrations() {
  stage "Supabase: database migrations (writes to PRODUCTION)"
  if [[ -z "${V_SESSION_DB_URL:-}" ]]; then
    todo_item "database migrations (no database values in this run)"
    return 0
  fi
  say "Compares supabase/migrations with the production database's migration history. Read-only first:"
  local output
  show_cmd "supabase db push --db-url <session-pooler-URL> --dry-run"
  if ! output=$(cd "$ROOT" && supabase db push --db-url "$V_SESSION_DB_URL" --dry-run </dev/null 2>&1); then
    mask "$output" | indent
    printf '\n'
    if [[ "$output" == *"inserted before the last migration"* || "$output" == *"not found in local migrations"* ]]; then
      note "The production history and supabase/migrations disagree: see the runbook, 'Migration out of order'."
    elif [[ "$output" == *"password authentication failed"* ]]; then
      note "Wrong database password (or the wrong project): check it, or reset it in Project Settings → Database."
    fi
    todo_item "database migrations (the dry run failed: see above and the runbook's Troubleshooting)"
    return 0
  fi
  mask "$output" | indent
  if [[ "$output" == *"is up to date"* ]]; then
    done_item "the production database is up to date: nothing to apply"
    return 0
  fi
  say ""
  warn "Applying them WRITES TO THE PRODUCTION DATABASE (tables, and the seed rules for item groups)."
  if confirm "Apply these migrations to production now?"; then
    act supabase db push --db-url "$V_SESSION_DB_URL" --yes || die "supabase db push failed (see above; nothing after the failing migration was applied)."
    ((DRY_RUN)) || done_item "migrations applied to production"
    note "Once Kreloses connections exist, a Sync now (any month) re-classifies items under the new rules"
    note "(README Item groups: a migration that adjusts seed rules shows from the next sync run)."
  else
    todo_item "apply the database migrations (supabase db push)"
  fi
}

stage_deploy() {
  stage "Deploy to production"
  if ((!VERCEL_OK)); then
    todo_item "deploy to production (sign in to Vercel first)"
    return 0
  fi
  local known_url="${PRODUCTION_URL:-}"
  [[ -n "$known_url" ]] || known_url=$(_existing PRODUCTION_URL || true)
  known_url="${known_url%/}"
  if [[ -n "$known_url" ]] && site_answers "$known_url"; then
    say "A production deployment already answers at $known_url."
    if ((ENV_CHANGED)); then
      say "Environment variables changed in this run: only a new deployment picks them up."
      if ! confirm "Deploy now?"; then
        todo_item "deploy again so the new environment variables apply"
        get_value PRODUCTION_URL text "Production URL:" "$known_url"
        return 0
      fi
    elif ! confirm "Deploy again anyway?"; then
      done_item "production deployment answering at $known_url"
      get_value PRODUCTION_URL text "Production URL:" "$known_url"
      save_value PRODUCTION_URL "$V_PRODUCTION_URL"
      return 0
    fi
  else
    say "Uploads this checkout (the clean main checked in stage 1; .vercelignore keeps local files such as"
    say ".env files and .claude/ out) and builds it on Vercel. Later pushes to main deploy by themselves."
    if ! confirm "Create the production deployment now?"; then
      todo_item "deploy to production (vercel deploy --prod)"
      return 0
    fi
  fi
  local deployment="" default_url="" aliases=""
  act_capture deployment vercel deploy --prod --yes --project "$PROJECT_NAME" "${VFLAGS[@]}" || die "vercel deploy failed: see the build output above."
  deployment=$(printf '%s\n' "$deployment" | grep -E '^https://' | tail -n 1 || true)
  if [[ -n "$deployment" ]]; then
    done_item "deployed: $deployment"
    aliases=$(probe vcs api "/v13/deployments/${deployment#https://}" --raw 2>/dev/null | jq -r '(.alias // [])[]' 2>/dev/null || true)
    # Prefer a custom domain, else the shortest *.vercel.app alias (the production domain).
    default_url=$(printf '%s\n' "$aliases" | grep -v '\.vercel\.app$' | grep . | head -n 1 || true)
    [[ -n "$default_url" ]] || default_url=$(printf '%s\n' "$aliases" | grep . | awk '{ print length, $0 }' | sort -n | head -n 1 | cut -d' ' -f2- || true)
    [[ -z "$default_url" ]] || default_url="https://$default_url"
  fi
  [[ -n "$default_url" ]] || default_url="$known_url"
  step "The production URL is the project's domain (Vercel → $PROJECT_NAME → Settings → Domains), not the"
  step "deployment's own URL above (that one sits behind Deployment Protection)."
  if ((DRY_RUN)) && [[ -z "${PRODUCTION_URL:-}$default_url" ]]; then
    note "(dry run: no production URL yet; later stages show placeholders)"
    return 0
  fi
  get_value PRODUCTION_URL text "Production URL:" "$default_url"
  save_value PRODUCTION_URL "$V_PRODUCTION_URL"
}

stage_auth() {
  stage "Supabase Auth: URLs, email templates, SMTP (in the dashboard)"
  local url="${V_PRODUCTION_URL:-https://<production-domain>}" ref="${SUPABASE_REF:-<project-ref>}" dash
  dash="https://supabase.com/dashboard/project/$ref"
  say "Set these by hand in the PRODUCTION project's dashboard. Never run 'supabase config push': the"
  say "local supabase/config.toml (localhost URLs, local settings) must never reach production."
  say ""
  say "${BOLD}1. Authentication → URL Configuration${RESET}"
  open_page "$dash/auth/url-configuration"
  step "Site URL: $url"
  step "Redirect URLs: exactly $url/auth/confirm and nothing else"
  note "   (remove localhost entries; never a wildcard such as https://*.vercel.app/**)"
  say "${BOLD}2. Authentication → Sign In / Providers → Email${RESET}"
  open_page "$dash/auth/providers"
  step "Confirm email: ON (keeps password sign-ups from ever getting a session)"
  step "Allow new users to sign up: ON (the app's allow-list decides who gets in; with it off the"
  step "first magic link to a new email fails)"
  say "${BOLD}3. Authentication → Emails → Templates: BOTH 'Magic Link' and 'Confirm signup'${RESET}"
  open_page "$dash/auth/templates"
  step "Subject: Your sign-in link"
  step "Body (from supabase/templates/magic_link.html):"
  if [[ -f "$ROOT/supabase/templates/magic_link.html" ]]; then indent <"$ROOT/supabase/templates/magic_link.html"; fi
  note "   The link must stay {{ .RedirectTo }}?token_hash={{ .TokenHash }}&type=email (works on any device)."
  say "${BOLD}4. Authentication → Emails → SMTP Settings: custom SMTP (strongly recommended)${RESET}"
  open_page "$dash/auth/smtp"
  step "Without it, Supabase's built-in email only reaches the project's team members and sends a"
  step "handful per hour: invited managers would get nothing. Use any SMTP provider you trust."
  note "If a link above 404s, the same page is under Authentication in the project's sidebar."
  say ""
  if ((DRY_RUN)); then
    todo_item "Supabase Auth settings (URL configuration, Confirm email, both email templates, SMTP)"
  elif confirm "Are all of these set in the production project?"; then
    done_item "Supabase Auth: site URL, redirect URL, Confirm email, both templates (confirmed by you)"
  else
    todo_item "Supabase Auth settings (URL configuration, Confirm email, both email templates, SMTP)"
  fi
}

stage_checks() {
  stage "Post-deploy checks"
  if [[ -z "${V_PRODUCTION_URL:-}" ]]; then
    todo_item "post-deploy checks (no production URL yet): scripts/deploy-wizard.sh --check https://<production-domain>"
    return 0
  fi
  say "Read-only requests to $V_PRODUCTION_URL; no secret is sent."
  if run_checks "$V_PRODUCTION_URL"; then
    done_item "production answers as expected (HTTPS, sign-in page, private dashboard, endpoints refuse without secrets)"
  else
    CHECKS_FAILED=1
    todo_item "fix the failed checks above, then: scripts/deploy-wizard.sh --check $V_PRODUCTION_URL"
  fi

  say ""
  if ((VERCEL_OK)); then
    local crons=""
    crons=$(probe vcs crons list --project "$PROJECT_NAME" 2>&1 || true)
    printf '%s\n' "$crons" | indent
    if [[ "$crons" == */api/cron/nightly* ]]; then
      done_item "Vercel Cron lists /api/cron/nightly (19:00 UTC = 03:00 KL, once a day on Hobby)"
    else
      open_page "https://vercel.com/${V_VERCEL_TEAM:-<team>}/$PROJECT_NAME/settings/cron-jobs"
      todo_item "check Vercel → $PROJECT_NAME → Settings → Cron Jobs lists /api/cron/nightly"
    fi
  fi

  say ""
  step "Now sign in: open $V_PRODUCTION_URL/login, enter ${V_OWNER_EMAIL:-the owner email}, open the email and"
  step "click 'Sign in'. You should land on the Overview page."
  open_page "$V_PRODUCTION_URL/login"
  if ((DRY_RUN)); then
    todo_item "sign in to production with a magic link"
  elif confirm "Did the magic-link sign-in work?"; then
    done_item "owner signed in to production with a magic link"
  else
    note "No email: custom SMTP (stage 9), or the email is not a Supabase team member. Link refused:"
    note "the redirect URL / template (stage 9). More in the runbook's Troubleshooting."
    todo_item "sign in to production with a magic link"
  fi
}

stage_kreloses() {
  stage "Kreloses: the live check, then the connections"
  local url="${V_PRODUCTION_URL:-https://<production-domain>}"
  say "1. The live check (issue #3), from this checkout, in zsh. One real login and a few page reads;"
  say "   it prints a redacted report (no names, amounts or ids):"
  printf '\n'
  printf '      %s\n' \
    'read -r "KRELOSES_TEST_EMAIL?Kreloses email: "; read -rs "KRELOSES_TEST_PASSWORD?Kreloses password: "; echo' \
    'export KRELOSES_TEST_EMAIL KRELOSES_TEST_PASSWORD' \
    'npm run test:live' \
    'KRELOSES_TEST_MONTH=2024-03 npm run test:live   # an old month: its Sale List page and a few invoice pages' \
    'unset KRELOSES_TEST_EMAIL KRELOSES_TEST_PASSWORD'
  printf '\n'
  say "   (bash: read -rp \"Kreloses email: \" KRELOSES_TEST_EMAIL; read -rsp \"Kreloses password: \" KRELOSES_TEST_PASSWORD)"
  say "   Look the report over, then paste it into issue #3: https://github.com/$REPO_SLUG/issues/3"
  say ""
  say "2. Add one connection per branch login: $url/connections (each is tested when saved)."
  say "3. Sync now for the current month, then compare a day or two with Kreloses."
  say "4. After any migration that changes item-group seed rules, press Sync now once (README Item groups)."
  open_page "$url/connections"
  if ((DRY_RUN)); then
    todo_item "live check → issue #3, then add the Kreloses connections"
    return 0
  fi
  if confirm "Have you run the live check and pasted the report into issue #3?"; then
    done_item "live check report pasted into issue #3"
  else
    todo_item "run npm run test:live and paste the redacted report into issue #3"
  fi
  if confirm "Are the Kreloses connections added and showing Connected?"; then
    done_item "Kreloses connections added"
  else
    todo_item "add the Kreloses connections ($url/connections)"
  fi
}

stage_backfill() {
  stage "History backfill (GitHub Actions trigger)"
  if [[ ! -f "$ROOT/.github/workflows/backfill.yml" ]]; then
    say "The history backfill (#8) is not on main yet. Run the wizard again after it merges: this stage"
    say "is then the only one with anything left to do."
    todo_item "history backfill: after #8 merges, run the wizard again"
    return 0
  fi
  say "The backfill reads every invoice since 1 Jan 2024 over about a week of nights. Turn it on only"
  say "after the live check confirmed the Reader's assumptions (README, 'UNVERIFIED until the live check'):"
  step "the Sale List's date filter is honoured by the server (the report's \"rows outside the requested range\" is 0)"
  step "SaleDate's time zone (the report's hour-of-day histogram: clinic hours at night mean KL time sent as UTC)"
  step "an invoice line's Amount is after its item discount"
  step "the sign of discount lines (type 55)"
  step "the shapes of RefundInfo and CreditNoteInfo"
  step "how a walk-in customer is represented"
  step "whether item lines also carry an invoice-level DiscountName/DiscountAmount"
  step "old invoice pages parse like recent ones: KRELOSES_TEST_MONTH=2024-03 npm run test:live (stage 11)"
  say "Then Sync now a 2024 month and compare a few of its invoices with their pages in Kreloses."
  if ! confirm "Reviewed all of that, and ready to turn the nightly backfill on?"; then
    todo_item "history backfill: review the live check, then run the wizard again"
    return 0
  fi
  if [[ -z "${V_PRODUCTION_URL:-}" ]]; then
    todo_item "history backfill (needs the production URL: deploy first)"
    return 0
  fi

  get_value GITHUB_OWNER text "GitHub account that owns $REPO_SLUG:" "$REPO_OWNER"
  local account="$V_GITHUB_OWNER" token="" secrets="" variables="" enabled=""
  token=$(probe gh auth token --user "$account" 2>/dev/null || true)
  if [[ -z "$token" ]]; then
    step "gh is not signed in as $account. In another terminal: gh auth login (as $account)"
    todo_item "history backfill: gh auth login as $account, then run the wizard again"
    return 0
  fi
  register_secret "$token"
  export GH_TOKEN="$token"
  DISPLAY_PREFIX="GH_TOKEN=\$(gh auth token --user $account) "
  secrets=$(probe gh secret list --repo "$REPO_SLUG" 2>/dev/null | cut -f1 | tr '\n' ' ' || true)
  variables=$(probe gh variable list --repo "$REPO_SLUG" 2>/dev/null || true)
  enabled=$(printf '%s\n' "$variables" | awk -F'\t' '$1 == "BACKFILL_ENABLED" { print $2 }')

  if in_list APP_URL "$secrets" && ! confirm "The repository secret APP_URL is already set. Replace it with $V_PRODUCTION_URL?"; then
    done_item "GitHub secret APP_URL already set: kept"
  else
    act_input "$V_PRODUCTION_URL" gh secret set APP_URL --repo "$REPO_SLUG" || die "Could not set APP_URL."
    ((DRY_RUN)) || done_item "GitHub secret APP_URL set"
  fi

  if in_list CRON_SECRET "$NEW_SECRETS"; then
    in_list CRON_SECRET "$secrets" && say "The app got a NEW CRON_SECRET in this run: GitHub's copy must match it."
    act_input "${V_CRON_SECRET:-}" gh secret set CRON_SECRET --repo "$REPO_SLUG" || die "Could not set CRON_SECRET."
    ((DRY_RUN)) || done_item "GitHub secret CRON_SECRET set (the app's value)"
  elif in_list CRON_SECRET "$secrets"; then
    done_item "GitHub secret CRON_SECRET already set: kept (it must equal the app's CRON_SECRET)"
  else
    local value="${V_CRON_SECRET:-}"
    if [[ -z "$value" ]]; then
      say "Vercel keeps CRON_SECRET write-only. Paste the copy you saved (or see the runbook to rotate it)."
      get_value CRON_SECRET_FOR_GITHUB secret "The app's CRON_SECRET (hidden input):"
      value="$V_CRON_SECRET_FOR_GITHUB"
    fi
    act_input "$value" gh secret set CRON_SECRET --repo "$REPO_SLUG" || die "Could not set CRON_SECRET."
    ((DRY_RUN)) || done_item "GitHub secret CRON_SECRET set"
  fi

  if [[ "$enabled" == true ]]; then
    done_item "GitHub variable BACKFILL_ENABLED is already true"
  else
    act gh variable set BACKFILL_ENABLED --body true --repo "$REPO_SLUG" || die "Could not set BACKFILL_ENABLED."
    ((DRY_RUN)) || done_item "GitHub variable BACKFILL_ENABLED = true: the backfill runs every 15 minutes, 00:00–06:00 KL"
  fi
  if confirm "Run the backfill workflow once by hand now? (outside 00:00–06:00 KL it answers 200 and does nothing)"; then
    act gh workflow run backfill.yml --repo "$REPO_SLUG" || warn "Could not start the workflow; try Actions → History backfill → Run workflow."
  fi
  note "Progress: $V_PRODUCTION_URL/sync. To stop it: gh variable set BACKFILL_ENABLED --body false --repo $REPO_SLUG"
  save_value GITHUB_OWNER "$account"
  unset GH_TOKEN
  DISPLAY_PREFIX=""
}

stage_summary() {
  stage "Summary"
  local item url="${V_PRODUCTION_URL:-https://<production-domain>}"
  if ((DRY_RUN)); then
    say "${BOLD}Dry run: nothing was changed.${RESET} ${#PLANNED[@]} command(s) would have run:"
    for item in ${PLANNED[@]+"${PLANNED[@]}"}; do note "  $item"; done
  fi
  say ""
  say "${BOLD}Done (${#DONE_ITEMS[@]})${RESET}"
  for item in ${DONE_ITEMS[@]+"${DONE_ITEMS[@]}"}; do printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$item"; done
  say "${BOLD}Still to do (${#TODO_ITEMS[@]})${RESET}"
  for item in ${TODO_ITEMS[@]+"${TODO_ITEMS[@]}"}; do printf '  %s…%s %s\n' "$YELLOW" "$RESET" "$item"; done
  ((${#TODO_ITEMS[@]})) || say "  nothing"

  say ""
  say "${BOLD}Connect Claude to the MCP server${RESET} (README, 'Connect Claude to the MCP server'):"
  if ((SAVE_ENABLED)); then
    note "The token is MCP_BEARER_TOKEN in $SAVE_FILE."
  else
    note "Use the MCP token you kept (Vercel stores it write-only)."
  fi
  printf '      %s\n' \
    'read -rs "KRELOSES_MCP_TOKEN?MCP token: "; echo' \
    "claude mcp add --scope user --transport http kreloses $url/api/mcp \\" \
    '  --header "Authorization: Bearer $KRELOSES_MCP_TOKEN"' \
    'unset KRELOSES_MCP_TOKEN'
  note "Never --scope project with a literal token: it would land in .mcp.json in this public repository."
  say ""
  say "${BOLD}Rotating secrets${RESET} (runbook, 'Rotating secrets'):"
  note "scripts/deploy-wizard.sh --rotate MCP_BEARER_TOKEN (or CRON_SECRET): a new value in Vercel, a"
  note "redeploy, and GitHub's CRON_SECRET updated; then give Claude the new MCP token."
  note "Keep Deployment Protection on (Standard): older deployments keep the old values, and it keeps"
  note "their URLs private. CREDENTIALS_ENCRYPTION_KEY is never rotated by the wizard: every Kreloses"
  note "password would have to be entered again."
  if ((SAVE_ENABLED)); then
    say ""
    note "Your copy: $SAVE_FILE (chmod 600). Move it into a password manager when you're done."
  fi
}

# ── Main ───────────────────────────────────────────────────────────────────────────────────────────
case "$MODE" in
  help)
    usage
    exit 0
    ;;
  list-env)
    list_env
    exit 0
    ;;
  check-env)
    check_env_complete
    exit $?
    ;;
  check)
    [[ -n "$CHECK_URL" ]] || die "--check needs the URL to check, e.g. --check https://example.vercel.app"
    setup_tmp
    printf '\n%s%s  Post-deploy checks: %s%s\n\n' "$BOLD" "$BLUE" "$CHECK_URL" "$RESET"
    if run_checks "$CHECK_URL"; then
      printf '\n  %sAll checks passed.%s\n' "$GREEN" "$RESET"
      exit 0
    fi
    printf '\n  %s%s check(s) failed.%s\n' "$RED" "$CHECK_FAILURES" "$RESET"
    exit 1
    ;;
esac

cd "$ROOT"
setup_tmp
trap 'printf "\n"; warn "Stopped. Run the wizard again to carry on: finished stages are detected and skipped."; exit 130' INT
if [[ -f "$SAVE_FILE" ]]; then
  SAVE_ENABLED=1
  ((DRY_RUN)) || chmod 600 "$SAVE_FILE"
fi

if ((DRY_RUN)); then
  banner "Production deploy: Kreloses Data Analytics (DRY RUN: nothing will be changed)"
else
  banner "Production deploy: Kreloses Data Analytics"
fi
((SAVE_ENABLED)) && note "Using the values saved in $SAVE_FILE by an earlier run."

stage_preflight
stage_vercel_login
stage_project
stage_secrets
stage_supabase
stage_env
stage_migrations
stage_deploy
stage_auth
stage_checks
stage_kreloses
stage_backfill
stage_summary
printf '\n'
